import { Piatto } from '../../app/model/menu.model';

export const ANTIPASTI: Piatto[] = [
  {
    nome: 'MENU.ANTIPASTI.BRUSCHETTA.NOME',
    ingredienti: 'MENU.ANTIPASTI.BRUSCHETTA.INGREDIENTI',
    prezzo: '5,50€',
  },
  {
    nome: 'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.NOME',
    ingredienti: [
      'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_INTRO',
      'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_1',
      'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_2',
      'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_3',
    ],
    prezzo: '8€',
  },
  {
    nome: 'MENU.ANTIPASTI.FRITTATINA_DI_PASTA.NOME',
    ingredienti: 'MENU.ANTIPASTI.FRITTATINA_DI_PASTA.INGREDIENTI',
    prezzo: '8€',
  },
  {
    nome: 'MENU.ANTIPASTI.PARMIGIANA_DI_MELANZANE.NOME',
    ingredienti: 'MENU.ANTIPASTI.PARMIGIANA_DI_MELANZANE.INGREDIENTI',
    prezzo: '8€',
  },
  {
    nome: 'MENU.ANTIPASTI.MOZZARELLA_IN_CARROZZA.NOME',
    ingredienti: 'MENU.ANTIPASTI.MOZZARELLA_IN_CARROZZA.INGREDIENTI',
    prezzo: '10€',
  },
  {
    nome: 'MENU.ANTIPASTI.IL_CUOPPO.NOME',
    ingredienti: 'MENU.ANTIPASTI.IL_CUOPPO.INGREDIENTI',
    prezzo: '14€',
  },
  {
    nome: 'MENU.ANTIPASTI.ZEPPOLE_ALLE_ALGHE.NOME',
    ingredienti: 'MENU.ANTIPASTI.ZEPPOLE_ALLE_ALGHE.INGREDIENTI',
    prezzo: '6€',
  },
  {
    nome: 'MENU.ANTIPASTI.LA_SCAMPAGNATA.NOME',
    ingredienti: [
      'MENU.ANTIPASTI.LA_SCAMPAGNATA.INGREDIENTI_1',
      'MENU.ANTIPASTI.LA_SCAMPAGNATA.INGREDIENTI_2',
      'MENU.ANTIPASTI.LA_SCAMPAGNATA.INGREDIENTI_3',
    ],
    prezzo: '25€',
  },
];
