import { Piatto } from '../../app/model/menu.model';

export const ANTIPASTI: Piatto[] = [
  // {
  //   nome: 'MENU.ANTIPASTI.BRUSCHETTA.NOME',
  //   ingredienti: 'MENU.ANTIPASTI.BRUSCHETTA.INGREDIENTI',
  // },
  {
    nome: 'MENU.ANTIPASTI.TAGLIERE_DI_BRUSCHETTE.NOME',
    ingredienti: [
      'MENU.ANTIPASTI.TAGLIERE_DI_BRUSCHETTE.INGREDIENTI_1',
      'MENU.ANTIPASTI.TAGLIERE_DI_BRUSCHETTE.INGREDIENTI_2',
      'MENU.ANTIPASTI.TAGLIERE_DI_BRUSCHETTE.INGREDIENTI_3',
    ],
  },
  {
    nome: 'MENU.ANTIPASTI.E_CURNICIELL.NOME',
    ingredienti: [
      'MENU.ANTIPASTI.E_CURNICIELL.INGREDIENTI_INTRO',
      'MENU.ANTIPASTI.E_CURNICIELL.INGREDIENTI_1',
      'MENU.ANTIPASTI.E_CURNICIELL.INGREDIENTI_2',
    ],
  },
  {
    nome: 'MENU.ANTIPASTI.LA_MULIGNANONA.NOME',
    ingredienti: 'MENU.ANTIPASTI.LA_MULIGNANONA.INGREDIENTI',
  },
  // {
  //   nome: 'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.NOME',
  //   ingredienti: [
  //     'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_INTRO',
  //     'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_1',
  //     'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_2',
  //     'MENU.ANTIPASTI.I_BACI_DI_SOPHIA.INGREDIENTI_3',
  //   ],
  // },
  // {
  //   nome: 'MENU.ANTIPASTI.FRITTATINA_DI_PASTA.NOME',
  //   ingredienti: 'MENU.ANTIPASTI.FRITTATINA_DI_PASTA.INGREDIENTI',
  // },
  // {
  //   nome: 'MENU.ANTIPASTI.PARMIGIANA_DI_MELANZANE.NOME',
  //   ingredienti: 'MENU.ANTIPASTI.PARMIGIANA_DI_MELANZANE.INGREDIENTI',
  // },
  // {
  //   nome: 'MENU.ANTIPASTI.MOZZARELLA_IN_CARROZZA.NOME',
  //   ingredienti: 'MENU.ANTIPASTI.MOZZARELLA_IN_CARROZZA.INGREDIENTI',
  // },
  {
    nome: 'MENU.ANTIPASTI.IL_CUOPPO.NOME',
    ingredienti: 'MENU.ANTIPASTI.IL_CUOPPO.INGREDIENTI',
  },
  {
    nome: 'MENU.ANTIPASTI.ZEPPOLE_ALLE_ALGHE.NOME',
    ingredienti: 'MENU.ANTIPASTI.ZEPPOLE_ALLE_ALGHE.INGREDIENTI',
  },
  {
    nome: 'MENU.ANTIPASTI.LA_SCAMPAGNATA.NOME',
    ingredienti: [
      'MENU.ANTIPASTI.LA_SCAMPAGNATA.INGREDIENTI_1',
      'MENU.ANTIPASTI.LA_SCAMPAGNATA.INGREDIENTI_2',
      'MENU.ANTIPASTI.LA_SCAMPAGNATA.INGREDIENTI_3',
    ],
  },
];
