import { Piatto } from '../../app/model/menu.model';

export const CANTINA: Piatto[] = [
  { nome: 'MENU.CANTINA.VINI_BIANCHI.CATEGORIA', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINI_BIANCHI.LACRYMA_CHRISTI_BIANCO.NOME', ingredienti: 'MENU.CANTINA.VINI_BIANCHI.LACRYMA_CHRISTI_BIANCO.INGREDIENTI' },
  { nome: 'MENU.CANTINA.VINI_BIANCHI.FALANGHINA_DEL_SANNIO.NOME', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINI_BIANCHI.GRECO_DI_TUFO.NOME', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINI_BIANCHI.FIANO_DI_AVELLINO.NOME', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINI_BIANCHI.FALANGHINA_CAMPANIA.NOME', ingredienti: 'MENU.CANTINA.VINI_BIANCHI.FALANGHINA_CAMPANIA.INGREDIENTI' },
  { nome: 'MENU.CANTINA.VINI_BIANCHI.FALANGHINA_POMPEIANO.NOME', ingredienti: '' },

  { nome: 'MENU.CANTINA.VINI_ROSSI.CATEGORIA', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINI_ROSSI.LACRYMA_CHRISTI_ROSSO.NOME', ingredienti: 'MENU.CANTINA.VINI_ROSSI.LACRYMA_CHRISTI_ROSSO.INGREDIENTI' },
  { nome: 'MENU.CANTINA.VINI_ROSSI.AGLIANICO_SANNIO.NOME', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINI_ROSSI.ROSSO_POMPEIANO.NOME', ingredienti: 'MENU.CANTINA.VINI_ROSSI.ROSSO_POMPEIANO.INGREDIENTI' },
  { nome: 'MENU.CANTINA.VINI_ROSSI.GRAGNANO_DOC.NOME', ingredienti: 'MENU.CANTINA.VINI_ROSSI.GRAGNANO_DOC.INGREDIENTI' },
  { nome: 'MENU.CANTINA.VINI_ROSSI.AGLIANICO_POMPEIANO.NOME', ingredienti: '' },

  { nome: 'MENU.CANTINA.VINI_ROSE.CATEGORIA', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINI_ROSE.LACRYMA_CHRISTI_ROSE.NOME', ingredienti: '' },

  { nome: 'MENU.CANTINA.VINO_DELLA_CASA.CATEGORIA', ingredienti: '' },
  { nome: 'MENU.CANTINA.VINO_DELLA_CASA.ROSSO_E_BIANCO_VIVACE.NOME', ingredienti: '' },

  { nome: 'MENU.CANTINA.SPUMANTI.CATEGORIA', ingredienti: '' },
  { nome: 'MENU.CANTINA.SPUMANTI.FERDINANDVS_I.NOME', ingredienti: 'MENU.CANTINA.SPUMANTI.FERDINANDVS_I.INGREDIENTI' },
  { nome: 'MENU.CANTINA.SPUMANTI.PROSECCO.NOME', ingredienti: '' },
  { nome: 'MENU.CANTINA.SPUMANTI.FRANCIACORTA_BRUT.NOME', ingredienti: '' },

  { nome: 'MENU.CANTINA.APERITIVI.CATEGORIA', ingredienti: '' },
  { nome: 'MENU.CANTINA.APERITIVI.PROSECCO_AL_CALICE.NOME', ingredienti: '' },
  { nome: 'MENU.CANTINA.APERITIVI.APEROL_CAMPARI_SPRITZ.NOME', ingredienti: '' },
  { nome: 'MENU.CANTINA.APERITIVI.SARTI_SPRITZ.NOME', ingredienti: 'MENU.CANTINA.APERITIVI.SARTI_SPRITZ.INGREDIENTI' },
];
