import { Piatto } from "../../app/model/menu.model";

export const CARNE: Piatto[] = [
    { nome: 'MENU.CARNE.BISTECCONE_DI_MANZO.NOME', ingredienti: 'MENU.CARNE.BISTECCONE_DI_MANZO.INGREDIENTI' },
    { nome: 'MENU.CARNE.MILLEFOGLIE_DI_POLLO_E_VERDURE_ALLA_BRACE.NOME', ingredienti: 'MENU.CARNE.MILLEFOGLIE_DI_POLLO_E_VERDURE_ALLA_BRACE.INGREDIENTI' },
    { nome: 'MENU.CARNE.COTOLETTA_NAPOLETANA.NOME', ingredienti: 'MENU.CARNE.COTOLETTA_NAPOLETANA.INGREDIENTI' }
];
