import { Piatto } from "../../app/model/menu.model";
export const INSALATONE: Piatto[] = [
  { nome: 'MENU.INSALATONE.PURO_DETOX.NOME', ingredienti: 'MENU.INSALATONE.PURO_DETOX.INGREDIENTI' },
  { nome: 'MENU.INSALATONE.CIACIELLA.NOME', ingredienti: 'MENU.INSALATONE.CIACIELLA.INGREDIENTI' },
  { nome: 'MENU.INSALATONE.PROSCIUTTELLA.NOME', ingredienti: 'MENU.INSALATONE.PROSCIUTTELLA.INGREDIENTI' },
  { nome: 'MENU.INSALATONE.CESARONA.NOME', ingredienti: 'MENU.INSALATONE.CESARONA.INGREDIENTI' },
  { nome: 'MENU.INSALATONE.TONNARA.NOME', ingredienti: 'MENU.INSALATONE.TONNARA.INGREDIENTI' },
  { nome: 'MENU.INSALATONE.MARINARELLA.NOME', ingredienti: 'MENU.INSALATONE.MARINARELLA.INGREDIENTI' },
  { nome: 'MENU.INSALATONE.BRESAOLELLA.NOME', ingredienti: 'MENU.INSALATONE.BRESAOLELLA.INGREDIENTI' }
];
