import { Piatto } from "../../app/model/menu.model";

export const PIZZE_INTEGRALI: Piatto[] = [
    { nome: 'MENU.INTEGRALI.CARCIOFINA.NOME', ingredienti: 'MENU.INTEGRALI.CARCIOFINA.INGREDIENTI' },
    { nome: 'MENU.INTEGRALI.BUFALA_E_PARMA.NOME', ingredienti: 'MENU.INTEGRALI.BUFALA_E_PARMA.INGREDIENTI' },
    { nome: 'MENU.INTEGRALI.PUMMAROLA_MARINARA.NOME', ingredienti: 'MENU.INTEGRALI.PUMMAROLA_MARINARA.INGREDIENTI' },
    // { nome: 'MENU.INTEGRALI.CREMA_DI_RADICCHIO_E_GORGONZOLA.NOME', ingredienti: 'MENU.INTEGRALI.CREMA_DI_RADICCHIO_E_GORGONZOLA.INGREDIENTI' },
    { nome: 'MENU.INTEGRALI.VERDURE_E_PESTO.NOME', ingredienti: 'MENU.INTEGRALI.VERDURE_E_PESTO.INGREDIENTI' }
];
