import { Piatto } from "../../app/model/menu.model";

export const PIZZE_INTEGRALI: Piatto[] = [

    { nome: 'MENU.INTEGRALI.CARCIOFINA.NOME', ingredienti: 'MENU.INTEGRALI.CARCIOFINA.INGREDIENTI', prezzo: '14,00€' },
    { nome: 'MENU.INTEGRALI.BUFALA_E_PARMA.NOME', ingredienti: 'MENU.INTEGRALI.BUFALA_E_PARMA.INGREDIENTI', prezzo: '13,00€' },
    { nome: 'MENU.INTEGRALI.PUMMAROLA_MARINARA.NOME', ingredienti: 'MENU.INTEGRALI.PUMMAROLA_MARINARA.INGREDIENTI', prezzo: '10,00€' },
    { nome: 'MENU.INTEGRALI.CREMA_DI_RADICCHIO_E_GORGONZOLA.NOME', ingredienti: 'MENU.INTEGRALI.CREMA_DI_RADICCHIO_E_GORGONZOLA.INGREDIENTI', prezzo: '14,00€' }
];