import { Piatto } from "../../app/model/menu.model";
export const MOZZARELLE: Piatto[] = [
    { nome: 'MENU.MOZZARELLE.CON_CUORE_DI_BUE.NOME', ingredienti: 'MENU.MOZZARELLE.CON_CUORE_DI_BUE.INGREDIENTI' },
    { nome: 'MENU.MOZZARELLE.CON_BRESAOLA_DI_BUFALA_E_ZUCCHINE.NOME', ingredienti: 'MENU.MOZZARELLE.CON_BRESAOLA_DI_BUFALA_E_ZUCCHINE.INGREDIENTI' },
    { nome: 'MENU.MOZZARELLE.CON_SALMONE_AFFUMICATO_E_AVOCADO.NOME', ingredienti: 'MENU.MOZZARELLE.CON_SALMONE_AFFUMICATO_E_AVOCADO.INGREDIENTI' },
    { nome: 'MENU.MOZZARELLE.CON_PROSCIUTTO_DI_PARMA.NOME', ingredienti: 'MENU.MOZZARELLE.CON_PROSCIUTTO_DI_PARMA.INGREDIENTI' },
    { nome: 'MENU.MOZZARELLE.CON_MIX_DI_POMODORI_E_RUCOLA.NOME', ingredienti: 'MENU.MOZZARELLE.CON_MIX_DI_POMODORI_E_RUCOLA.INGREDIENTI' }
];
