import { Piatto } from "../../app/model/menu.model";
export const PASTA: Piatto[] = [
    { nome: 'MENU.PASTA.GNOCCHI_DI_PATATE.NOME', ingredienti: 'MENU.PASTA.GNOCCHI_DI_PATATE.INGREDIENTI' },
    { nome: 'MENU.PASTA.PACCHERI_ALLA_NERANO.NOME', ingredienti: 'MENU.PASTA.PACCHERI_ALLA_NERANO.INGREDIENTI' },
    { nome: 'MENU.PASTA.SCIALATIELLI_VERDURE_E_PESTO.NOME', ingredienti: 'MENU.PASTA.SCIALATIELLI_VERDURE_E_PESTO.INGREDIENTI' },
    { nome: 'MENU.PASTA.FUSILLONI_CREMA_DI_CARCIOFI_E_SALSICCIA.NOME', ingredienti: 'MENU.PASTA.FUSILLONI_CREMA_DI_CARCIOFI_E_SALSICCIA.INGREDIENTI' }
];
