import { Piatto } from "../../app/model/menu.model";

export const PIZZE: Piatto[] = [
  { nome: 'MENU.PIZZE.MARINARA.NOME', ingredienti: 'MENU.PIZZE.MARINARA.INGREDIENTI' },
  { nome: 'MENU.PIZZE.MARGHERITA.NOME', ingredienti: 'MENU.PIZZE.MARGHERITA.INGREDIENTI' },
  { nome: 'MENU.PIZZE.MARGHERITA_PROVOLA_E_PEPE.NOME', ingredienti: 'MENU.PIZZE.MARGHERITA_PROVOLA_E_PEPE.INGREDIENTI' },
  { nome: 'MENU.PIZZE.COSACCA.NOME', ingredienti: 'MENU.PIZZE.COSACCA.INGREDIENTI' },
  { nome: 'MENU.PIZZE.DIAVOLA.NOME', ingredienti: 'MENU.PIZZE.DIAVOLA.INGREDIENTI' },
  { nome: 'MENU.PIZZE.NAPOLI.NOME', ingredienti: 'MENU.PIZZE.NAPOLI.INGREDIENTI' },
  { nome: 'MENU.PIZZE.BIANCA_COTTO_E_FUNGHI.NOME', ingredienti: 'MENU.PIZZE.BIANCA_COTTO_E_FUNGHI.INGREDIENTI' },
  { nome: 'MENU.PIZZE.LA_DOC.NOME', ingredienti: 'MENU.PIZZE.LA_DOC.INGREDIENTI' },
  { nome: 'MENU.PIZZE.FUOCO_PURO.NOME', ingredienti: 'MENU.PIZZE.FUOCO_PURO.INGREDIENTI' },
  { nome: 'MENU.PIZZE.CAPRICCIOSA.NOME', ingredienti: 'MENU.PIZZE.CAPRICCIOSA.INGREDIENTI' },
  { nome: 'MENU.PIZZE.PARMENSE.NOME', ingredienti: 'MENU.PIZZE.PARMENSE.INGREDIENTI' },
  { nome: 'MENU.PIZZE.CINQUE_FORMAGGI.NOME', ingredienti: 'MENU.PIZZE.CINQUE_FORMAGGI.INGREDIENTI' },
  { nome: 'MENU.PIZZE.DONNA_LAURA.NOME', ingredienti: 'MENU.PIZZE.DONNA_LAURA.INGREDIENTI' },
  { nome: 'MENU.PIZZE.MORTADELLA_E_PANZEROTTO.NOME', ingredienti: 'MENU.PIZZE.MORTADELLA_E_PANZEROTTO.INGREDIENTI' },
  { nome: 'MENU.PIZZE.TONNO_E_CIPOLLA_ROSSA.NOME', ingredienti: 'MENU.PIZZE.TONNO_E_CIPOLLA_ROSSA.INGREDIENTI' },
  { nome: 'MENU.PIZZE.LA_CAFONA.NOME', ingredienti: 'MENU.PIZZE.LA_CAFONA.INGREDIENTI' }
];
