import { Piatto } from "../../app/model/menu.model";

export const RIPIENE: Piatto[] = [
    { nome: 'MENU.RIPIENE.CALZONE_AL_COTTO.NOME', ingredienti: 'MENU.RIPIENE.CALZONE_AL_COTTO.INGREDIENTI' },
    // { nome: 'MENU.RIPIENE.CALZONE_ALLA_SCAROLA.NOME', ingredienti: 'MENU.RIPIENE.CALZONE_ALLA_SCAROLA.INGREDIENTI' },
    { nome: 'MENU.RIPIENE.CALZONE_AL_SALAME.NOME', ingredienti: 'MENU.RIPIENE.CALZONE_AL_SALAME.INGREDIENTI' },
    // { nome: 'MENU.RIPIENE.SOLE_LUNA.NOME', ingredienti: 'MENU.RIPIENE.SOLE_LUNA.INGREDIENTI' }
];
