import { Piatto } from "../../app/model/menu.model";

export const STAGIONALI: Piatto[] = [
    { nome: 'MENU.STAGIONALI.SCARPETTA.NOME', ingredienti: 'MENU.STAGIONALI.SCARPETTA.INGREDIENTI' },
    { nome: 'MENU.STAGIONALI.NERANO.NOME', ingredienti: 'MENU.STAGIONALI.NERANO.INGREDIENTI' },
    { nome: 'MENU.STAGIONALI.PERLINE_E_POMODORINI.NOME', ingredienti: 'MENU.STAGIONALI.PERLINE_E_POMODORINI.INGREDIENTI' },
    { nome: 'MENU.STAGIONALI.BRESAOLA_E_ZUCCHINE.NOME', ingredienti: 'MENU.STAGIONALI.BRESAOLA_E_ZUCCHINE.INGREDIENTI' },
    {
        nome: 'MENU.STAGIONALI.LA_3_GUSTI.NOME',
        ingredienti: [
            'MENU.STAGIONALI.LA_3_GUSTI.INGREDIENTI_1',
            'MENU.STAGIONALI.LA_3_GUSTI.INGREDIENTI_2',
            'MENU.STAGIONALI.LA_3_GUSTI.INGREDIENTI_3',
        ]
    }
];
