import { Piatto } from "../../app/model/menu.model";

export const STAGIONALI: Piatto[] = [
    { nome: 'MENU.STAGIONALI.SALSICCIA_E_FRIARIELLI.NOME', ingredienti: 'MENU.STAGIONALI.SALSICCIA_E_FRIARIELLI.INGREDIENTI', prezzo: '11€' },
    { nome: 'MENU.STAGIONALI.RAGU_E_POLPETTINE.NOME', ingredienti: 'MENU.STAGIONALI.RAGU_E_POLPETTINE.INGREDIENTI', prezzo: '12€' },
    { nome: 'MENU.STAGIONALI.ANGRISELLA.NOME', ingredienti: 'MENU.STAGIONALI.ANGRISELLA.INGREDIENTI', prezzo: '11,50€' },
    { nome: 'MENU.STAGIONALI.CACIO_E_PEPE.NOME', ingredienti: 'MENU.STAGIONALI.CACIO_E_PEPE.INGREDIENTI', prezzo: '11€' },
    { nome: 'MENU.STAGIONALI.PUVERELLA.NOME', ingredienti: 'MENU.STAGIONALI.PUVERELLA.INGREDIENTI', prezzo: '11€' }

];